package com.glassestoredb.entity2;
// Generated 21 juin 2020 11:00:46 by Hibernate Tools 5.3.16.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private int categoryId;
	private String name;
	private Set glasseses = new HashSet(0);

	public Category() {
	}

	public Category(int categoryId, String name) {
		this.categoryId = categoryId;
		this.name = name;
	}

	public Category(int categoryId, String name, Set glasseses) {
		this.categoryId = categoryId;
		this.name = name;
		this.glasseses = glasseses;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getGlasseses() {
		return this.glasseses;
	}

	public void setGlasseses(Set glasseses) {
		this.glasseses = glasseses;
	}

}
