package com.glassestoredb.entity2;
// Generated 21 juin 2020 11:00:46 by Hibernate Tools 5.3.16.Final

/**
 * OrderDetailId generated by hbm2java
 */
public class OrderDetailId implements java.io.Serializable {

	private Integer orderId;
	private Integer glassesId;
	private int quantity;
	private float subtotal;

	public OrderDetailId() {
	}

	public OrderDetailId(int quantity, float subtotal) {
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	public OrderDetailId(Integer orderId, Integer glassesId, int quantity, float subtotal) {
		this.orderId = orderId;
		this.glassesId = glassesId;
		this.quantity = quantity;
		this.subtotal = subtotal;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getGlassesId() {
		return this.glassesId;
	}

	public void setGlassesId(Integer glassesId) {
		this.glassesId = glassesId;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(float subtotal) {
		this.subtotal = subtotal;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailId))
			return false;
		OrderDetailId castOther = (OrderDetailId) other;

		return ((this.getOrderId() == castOther.getOrderId()) || (this.getOrderId() != null
				&& castOther.getOrderId() != null && this.getOrderId().equals(castOther.getOrderId())))
				&& ((this.getGlassesId() == castOther.getGlassesId()) || (this.getGlassesId() != null
						&& castOther.getGlassesId() != null && this.getGlassesId().equals(castOther.getGlassesId())))
				&& (this.getQuantity() == castOther.getQuantity()) && (this.getSubtotal() == castOther.getSubtotal());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37 * result + (getGlassesId() == null ? 0 : this.getGlassesId().hashCode());
		result = 37 * result + this.getQuantity();
		result = 37 * result + (int) this.getSubtotal();
		return result;
	}

}
