package com.glassestore.entity;
// Generated 9 juin 2020 15:44:55 by Hibernate Tools 5.3.16.Final

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private OrderDetailId id;
	private Glasses glasses;
	private GlassesOrder glassesOrder;

	public OrderDetail() {
	}

	public OrderDetail(OrderDetailId id) {
		this.id = id;
	}

	public OrderDetail(OrderDetailId id, Glasses glasses, GlassesOrder glassesOrder) {
		this.id = id;
		this.glasses = glasses;
		this.glassesOrder = glassesOrder;
	}

	public OrderDetailId getId() {
		return this.id;
	}

	public void setId(OrderDetailId id) {
		this.id = id;
	}

	public Glasses getGlasses() {
		return this.glasses;
	}

	public void setGlasses(Glasses glasses) {
		this.glasses = glasses;
	}

	public GlassesOrder getGlassesOrder() {
		return this.glassesOrder;
	}

	public void setGlassesOrder(GlassesOrder glassesOrder) {
		this.glassesOrder = glassesOrder;
	}

}
